### ISSUE TITLE
Details on setting up Solr for Kubernetes deployment

### ISSUE THREAD

**Issue by fuero** [UnitedPlanet/intrexx-cloud-playbooks#12]
Hi,

how is Solr supposed to be used when deploying on Kubernetes?
The guide just says "Install SolrCloud", and references the solr image created during image creation, but that's it.

I've tried by just deploying the Solr image that was created, but the portal server is unwilling to use it:

```
java.lang.RuntimeException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.apache.solr.common.SolrException: java.lang.IllegalArgumentException: Invalid path string &quot;//ixcloudsolr:8983/solr&quot; caused by empty node name specified @1
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
```

That's with the defaults after using the `build_image_podman.sh` script.

Switching to HTTP doesn't make a difference.

That's the deployment & service I used for Solr:

```yaml
---
kind: Service
apiVersion: v1
metadata:
  name: ixcloudsolr
  namespace: intrexx2103
spec:
  selector:
    app: ixcloudsolr
  ports:
    - protocol: TCP
      port: 8983
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixcloudsolr
  labels:
    app: ixcloudsolr
  namespace: intrexx2103
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ixcloudsolr
  template:
    metadata:
      labels:
        app: ixcloudsolr
    spec:
      containers:
      - image: mycorp/ixcloudsolr
        name: ixcloud-solr
        imagePullPolicy: Always
        command: ["/opt/intrexx/bin/linux/upixsolr"]
        args: ["console"]
        tty: true
        volumeMounts:
        - mountPath: /opt/intrexx/org/cloud
          subPath: intrexx2103/portal
          name: ixcloud-volume
        - mountPath: /opt/intrexx/bin
          subPath: intrexx2103/bin
          name: ixcloud-volume
        - mountPath: /opt/intrexx/cfg
          subPath: intrexx2103/cfg
          name: ixcloud-volume
      volumes:
        - name: ixcloud-volume
          nfs:
            server: 192.168.178.1
            path: /
```

I verified that the portal service is able to reach the service and the response seems sane (at least through curl).

Please provide clear instructions on how to setup Solr.
